### ISSUE TITLE
LabExT does not start on macOS

### ISSUE THREAD

**Issue by maltewae** [LabExT/LabExT#79]
**Describe the bug**
LabExT does not start on macOS.

**To Reproduce**
On macOS 
```bash
conda create -n LabExT_env python=3.8
conda activate LabExT_env
pip install -r requirements.txt
pip install -e .
LabExT
```

**Expected behavior**
The LabExT window is loaded.

**Traceback**
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/LabExT_env/bin/LabExT", line 33, in <module>
    sys.exit(load_entry_point('LabExT-pkg', 'console_scripts', 'LabExT')())
  File "/Users/maltewae/src/github.com/maltewae/LabExT/LabExT/Main.py", line 105, in main
    ExperimentManager(tk_root, log_file_path)
  File "/Users/maltewae/src/github.com/maltewae/LabExT/LabExT/ExperimentManager.py", line 102, in __init__
    self.pgb = ProgressBar(root, 'Welcome to LabExt\nWe are setting everything up for you!')
  File "/Users/maltewae/src/github.com/maltewae/LabExT/LabExT/View/ProgressBar/ProgressBar.py", line 31, in __init__
    self.overrideredirect(True)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/LabExT_env/lib/python3.8/tkinter/__init__.py", line 2176, in wm_overrideredirect
    return self._getboolean(self.tk.call(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/LabExT_env/lib/python3.8/tkinter/__init__.py", line 1448, in _getboolean
    return self.tk.getboolean(string)
_tkinter.TclError: expected boolean value but got ""
```

**Desktop (please complete the following information):**
 - Operating System: macOS 12.3.1 (Build: 21E258)
 - Python environment: Python 3.8.13 (ARM), 
 - LabExT Version or Git revision: `dev` (`385a0cc73c250ccbfd9bf6a5bccd45069f519e25`)
 - Installed packages:
```
astunparse                1.6.3                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
autopep8                  1.6.0                    pypi_0    pypi
bidict                    0.21.4                   pypi_0    pypi
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.5.18.1          h4653dfc_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
collision                 1.2.2                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
distlib                   0.3.4                    pypi_0    pypi
filelock                  3.7.0                    pypi_0    pypi
flaky                     3.7.0                    pypi_0    pypi
fonttools                 4.33.3                   pypi_0    pypi
ghp-import                2.1.0                    pypi_0    pypi
h5py                      3.6.0                    pypi_0    pypi
importlib-metadata        4.11.3                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
kiwisolver                1.4.2                    pypi_0    pypi
labext-pkg                2.1.2                     dev_0    <develop>
libffi                    3.4.2                h3422bc3_5    conda-forge
libzlib                   1.2.11            h90dfc92_1014    conda-forge
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
mergedeep                 1.3.4                    pypi_0    pypi
mkdocs                    1.3.0                    pypi_0    pypi
mkdocs-autorefs           0.4.1                    pypi_0    pypi
mkdocs-material           8.2.14                   pypi_0    pypi
mkdocs-material-extensions 1.0.3                    pypi_0    pypi
mkdocstrings              0.18.1                   pypi_0    pypi
mkdocstrings-python-legacy 0.2.2                    pypi_0    pypi
ncurses                   6.3                  h07bb92c_1    conda-forge
numpy                     1.21.6                   pypi_0    pypi
openssl                   3.0.3                ha287fd2_0    conda-forge
packaging                 21.3                     pypi_0    pypi
parameterized             0.8.1                    pypi_0    pypi
pillow                    9.1.0                    pypi_0    pypi
pip                       22.1.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pymdown-extensions        9.4                      pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyserial                  3.5                      pypi_0    pypi
pytest                    7.1.2                    pypi_0    pypi
pytest-xvfb               2.0.0                    pypi_0    pypi
python                    3.8.13          hd3575e6_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytkdocs                  0.16.1                   pypi_0    pypi
pyusb                     1.2.1                    pypi_0    pypi
pyvirtualdisplay          3.0                      pypi_0    pypi
pyvisa                    1.12.0                   pypi_0    pypi
pyvisa-py                 0.5.3                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyyaml-env-tag            0.1                      pypi_0    pypi
readline                  8.1                  hedafd6a_0    conda-forge
scipy                     1.7.3                    pypi_0    pypi
setuptools                62.3.2           py38h10201cd_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sqlite                    3.38.5               h40dfcc0_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tox                       3.25.0                   pypi_0    pypi
ttkwidgets                0.12.1                   pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
virtualenv                20.14.1                  pypi_0    pypi
watchdog                  2.1.7                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zipp                      3.8.0                    pypi_0    pypi
zlib                      1.2.11            h90dfc92_1014    conda-forge
```

**Additional context**
Commenting out the following line solves the problem: https://github.com/LabExT/LabExT/blob/dev/LabExT/View/ProgressBar/ProgressBar.py#L31

**Comment by delmedico** [comment]
thank you @maltewae, it's the same for me except for Python 3.9.12

**Comment by marcoep** [comment]
So, this apparently is a known bug of tkinter. I will add a OS dependent skip of the offending line just to have a workaround for MacOS.
